spring:
  application:
    name: auth-service
server:
  port: 1300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
#    operationsSorter: method