spring:
  application:
    name: gateway-service  
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/sample/**,/auth/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/*
        filters:
        - AuthFilter
server:
  port: 1220

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka
      
